spring:
  datasource:
    url: postgresql://postgres:11Em3kVEMbCm3HvTwtS9@containers-us-west-166.railway.app:7174/railway
    username: postgres
    password: 11Em3kVEMbCm3HvTwtS9
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
